set_property IOSTANDARD LVCMOS33 [get_ports {disp_rgb[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp_rgb[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp_rgb[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp_rgb[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp_rgb[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp_rgb[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp_rgb[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp_rgb[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp_rgb[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp_rgb[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp_rgb[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp_rgb[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports hsync]
set_property IOSTANDARD LVCMOS33 [get_ports vsync]
set_property PACKAGE_PIN P17 [get_ports clk]
set_property PACKAGE_PIN D7 [get_ports hsync]
set_property PACKAGE_PIN C4 [get_ports vsync]
set_property PACKAGE_PIN B7 [get_ports {disp_rgb[11]}]
set_property PACKAGE_PIN C5 [get_ports {disp_rgb[10]}]
set_property PACKAGE_PIN C6 [get_ports {disp_rgb[9]}]
set_property PACKAGE_PIN F5 [get_ports {disp_rgb[8]}]
set_property PACKAGE_PIN D8 [get_ports {disp_rgb[7]}]
set_property PACKAGE_PIN A5 [get_ports {disp_rgb[6]}]
set_property PACKAGE_PIN A6 [get_ports {disp_rgb[5]}]
set_property PACKAGE_PIN B6 [get_ports {disp_rgb[4]}]
set_property PACKAGE_PIN E7 [get_ports {disp_rgb[3]}]
set_property PACKAGE_PIN E5 [get_ports {disp_rgb[2]}]
set_property PACKAGE_PIN E6 [get_ports {disp_rgb[1]}]
set_property PACKAGE_PIN C7 [get_ports {disp_rgb[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN N4 [get_ports rst]

set_property IOSTANDARD LVCMOS33 [get_ports key_clk]
set_property IOSTANDARD LVCMOS33 [get_ports key_data]
set_property PACKAGE_PIN K5 [get_ports key_clk]
set_property PACKAGE_PIN L4 [get_ports key_data]

set_property IOSTANDARD LVCMOS33 [get_ports flag_player]
set_property PACKAGE_PIN R1 [get_ports flag_player]

set_property IOSTANDARD LVCMOS33 [get_ports pwm]
set_property PACKAGE_PIN T1 [get_ports pwm]

